Clases ASP/Controllers/InteresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectosASP.Controllers
{
    public class InteresController : Controller
    {
        // GET: Interes
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult calcularInteresAnual()
        {
            string concact = "";
            int calcular = 0;
            int interes = 30045;
            for (int i = 0; i <=8; i++)
            {
                calcular = i * interes;
                concact += $"{interes}% x {i}Años = {calcular}<br/>";
            }
            return Content(concact);
        }
    }
}

Clases ASP/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectosASP.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult procesarLogin(string usuario, string clave)
        {
            ViewBag.mensaje = "";
            if (usuario == "starlin" && clave == "123456")
            {
                ViewBag.mensaje = "El usuario y password son correctos!";
                
            }else
            {
                ViewBag.mensaje = "El usuario y/o password es incorrecto!";
                
            }
            return View();
        }

    }
}

Clases ASP/Controllers/NotaFinalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectosASP.Controllers
{
    public class NotaFinalController : Controller
    {
        // GET: NotaFinal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult notaFinal1(int nota)
        {
            string diag = "";
            if(nota <= 69)
            {
                diag = $"Su nota final es: {nota} su calificacion es: D";
            }
            else if (nota >= 70 && nota <= 79)
            {
                diag = $"Su nota final es: {nota} su calificacion es: C";
            }
            else if (nota >=80 && nota <= 89)
            {
                diag = $"Su nota final es: {nota} su calificacion es: B";
            }
            else if (nota >= 90 && nota <= 100)
            {
                diag = $"Su nota final es: {nota} su calificacion es: A";
            }
            return Content(diag);
        }
    }
}

Clases ASP/Controllers/Numerosde10Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectosASP.Controllers
{
    public class Numerosde10Controller : Controller
    {
        // GET: Numerosde10
        public ActionResult Index()
        {
            return View();
        }
        public  ActionResult Numeros()
        {
            
            string concact = "";
            for (int i = 600; i <= 800; i+=10)
            {
                concact = concact +" " + i.ToString();
                
            }
           
            return Content($"Numero : {concact}");
        }
    }
}

Clases ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ejercicios ASP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ejercicios ASP <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li>@Html.ActionLink("Promedio", "index", "Promedio")</li>
                        <li>@Html.ActionLink("Loging", "index", "Login")</li>
                        <li>@Html.ActionLink("Nota final", "index", "NotaFinal")</li>
                        <li>@Html.ActionLink("Ingresar nota final", "index", "IngresarNota")</li>
                        <li>@Html.ActionLink("Login Infotep", "index", "LoginInfotep")</li>
                        <li>@Html.ActionLink("Numeros de 10 en 10", "Numeros", "Numerosde10")</li>
                        <li>@Html.ActionLink("Numeros de 1 - 1", "numerosDescendentes", "NumerosDescendentes")</li>
                        <li>@Html.ActionLink("Numeros 6x6", "tablamulti", "Tabladel6")</li>
                        <li>@Html.ActionLink("Multiplicar por Teclado", "Index", "TablaPorTeclado")</li>
                        <li>@Html.ActionLink("10% Interes", "calcularInteresAnual", "Interes")</li>
                        <li>@Html.ActionLink("Interes por teclado", "index", "aniosDeseados")</li>
                        <li>@Html.ActionLink("Numero random 1 al 100", "index", "NumeroRandom100")</li>
                        <li>@Html.ActionLink("Arreglo random", "matrizRandom", "NumeroRandomMatriz")</li>
                        <li>@Html.ActionLink("Numero random", "index", "RandomParametro")</li>
                    </ul>
                </li>
            </div>
        </div>
        </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>